name: bithovin
description: Various cryptographic tools with special focus on Bitcoin.
repository: https://github.com/astorDev/bithovin
version: 2024.106.1010001

environment:
  sdk: ^3.2.5

dependencies:
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
